# Copyright (c) 2022-2025, Tranquil Data, Inc. All rights reserved.

openapi: 3.0.0

info:
  title: Tranquil Data (TM) Enterprise Edition APIs
  description: >
    This is the complete API for the engine. It covers routines for provisioning
    entity state, managing subject context, exporting datastore access, and checking
    on the overall health of a service and its components.
  version: 1.0.1
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

externalDocs:
  description: "Find out more about Tranquil Data"
  url: "https://tranquildata.com"

tags:
  - name: root
    description: Local peer routines

servers:
  - url: http://localhost

paths:

  #
  # Root API paths
  #

  /:

    head:
      tags:
        - root
      summary: Test that this peer is running and ready
      operationId: checkPeer
      responses:
        '200':
          description: The peer is available and responsive
        '500':
          description: There is some internal error with the peer

    options:
      tags:
        - root
      summary: Returns the names of all services exposed by this peer
      operationId: getServices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './root_schema.yaml#/components/schemas/ServiceList'
              example:
                services:
                  - context
                  - datastores
                  - metrics
        '500':
          description: There is some internal error with the peer

    get:
      tags:
        - root
      summary: Returns details of the responding peer
      operationId: getPeerDetail
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './root_schema.yaml#/components/schemas/PeerDetail'
              example:
                identifier: 1
                certificate: AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
        '500':
          description: There is some internal error with the peer
